spring:
  application.name: https

#server:
#  port: 8443
#  ssl:
#    key-store: ./keystore.p12
#    key-store-password: rootroot
#    key-store-type: PKCS12
#    key-alias: testkey
hello: default
---
spring.config.activate.on-profile: prod
hello: prod
