on:
  push:
    paths:
      - client/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: project build
        run:
          chmod +x gradlew && ./gradlew clean build

      - name: set up docker
        uses: docker/setup-buildx-action@v3

      - name: docker image build
        run:
          docker build --file .docker/client-app.Dockerfile -t plll0123 .

