on:
  push:
    paths:
      - client/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: project build
        run:
          chmod +x gradlew && ./gradlew clean build

      - name: set up docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_PRIVATE_KEY }}
          aws-region: ap-northeast-2

      - name: build docker and push
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}
          docker build --file .docker/client-app.Dockerfile -t client-app .
          docker tag client-app:latest ${{ secrets.ECR_URL }}:latest
          docker push ${{ secrets.ECR_URL }}:latest

##
  deploy:
    needs: build
    runs-on: client-host-runner
    steps:
      - name: Install unzip if not present
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Check and install AWS CLI
        run: |
          cd ~
          if ! command -v aws &> /dev/null
          then
              echo "AWS CLI not found. Installing..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
          else
              echo "AWS CLI is already installed."
          fi