on:
  push:
    paths:
      - client/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: project build
        run:
          chmod +x gradlew && ./gradlew clean build

      - name: set up docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_PRIVATE_KEY }}
          aws-region: ap-northeast-2

      - name: docker image build and push aws
        run: |
          docker build --file .docker/client-app.Dockerfile -t plll0123 .
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }} 
