name: http goals

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 

      - name: checkout
        uses: actions/checkout@v4

      - name: java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: project build
        run:
          chmod +x gradlew && ./gradlew clean build

      - name: docker build
        run:
          docker build --file .docker/prod.Dockerfile --tag prod:latest .
