name: http goals

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: project build
        run:
          chmod +x gradlew && ./gradlew clean build

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build
        run:
          docker build . --file .docker/prod.Dockerfile --tag plll0123/prod
      - name: aws authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS }}
          aws-secret-access-key: ${{ secrets.ECR_PRIVATE }}
          aws-region: ap-northeast-2
      - name: push image
        run: |
          docker push 
        
