name: http goals

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 

      - name: checkout
        uses: actions/checkout@v4

      - name: java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: project build
        run:
          chmod +x gradlew && ./gradlew clean build

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: catd
        run: ls -al
      - name: docker build, push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/prod.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prod
        # run:
        #   docker build --file .docker/prod.Dockerfile --tag prod:latest .
