name: http goals

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: java build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: project build
        run:
          chmod +x gradlew && ./gradlew clean build

      # - name: docker login
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build
        run: |
          docker build --file .docker/prod.Dockerfile -t prod .
          docker tag prod:latest ${{ secrets.ECR_URL }}/pll0123:latest
      - name: aws authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS }}
          aws-secret-access-key: ${{ secrets.ECR_PRIVATE }}
          aws-region: ap-northeast-2
      - name: authentication aws docker
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}
          
      - name: push image
        run: |
          docker push ${{ secrets.ECR_URL }}/prod:latest
        
